#!/bin/bash
npx electron-icon-maker --input=../../design/logo/round.png --output=icons
cp -r icons/ assets/
rm -r icons/

echo formatting files...

mv assets/icons/mac/* assets/icons
mv assets/icons/win/* assets/icons
mv assets/icons/png/* assets/icons

rm -r assets/icons/mac/ assets/icons/win/ assets/icons/png/
echo all good
